package software.coley.instrument.util;

import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.IOException;

/**
 * Utility to facilitate generating byte array content.
 *
 * @author Matt Coley
 */
public class ByteGen {
	private final ByteArrayOutputStream out = new ByteArrayOutputStream();
	private final DataOutputStream stream = new DataOutputStream(out);

	/**
	 * @param data
	 * 		String to append.
	 *
	 * @return Self.
	 */
	public ByteGen appendString(String data) {
		try {
			stream.writeUTF(data);
			return this;
		} catch (IOException ex) {
			throw new IllegalStateException(ex);
		}
	}

	/**
	 * @param data
	 * 		int to append.
	 *
	 * @return Self.
	 */
	public ByteGen appendInt(int data) {
		try {
			stream.writeInt(data);
			return this;
		} catch (IOException ex) {
			throw new IllegalStateException(ex);
		}
	}

	/**
	 * @param data
	 * 		array to append.
	 *
	 * @return Self.
	 */
	public ByteGen appendByteArray(byte[] data) {
		try {
			stream.writeInt(data.length);
			stream.write(data);
			return this;
		} catch (IOException ex) {
			throw new IllegalStateException(ex);
		}
	}

	/**
	 * @return Generated byte array.
	 */
	public byte[] build() {
		return out.toByteArray();
	}
}
