name: Test Multi OS

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-latest, windows-2019, windows-latest, macos-11, macos-latest ]
        java-version: [ 8, 11, 12, 13, 14, 15, 16, 17, 18, 19 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt-hotspot
          java-version: ${{ matrix.java-version }}

      - name: Java version
        run: java -version

      # The project version extract NEEDS to have the maven wrapper already downloaded.
      # So we have a dummy step here just to initialize it.
      - name: Download maven wrapper
        run: ./mvnw --version

      - name: Build and Test
        run: ./mvnw test
